// auth signup
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test9@gmail.com",
    "password": "sjdfhq347"
}

#####

// signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test9@gmail.com",
    "password": "sjdfhq347"
}

#####

//signout
POST http://localhost:3000/auth/signout 

// find user
GET http://localhost:3000/auth/2
content-type: application/json

#####

// find all users with email
GET http://localhost:3000/auth?email=test@gmail.com
content-type: application/json

#####

// update user
PATCH  http://localhost:3000/auth/1
content-type: application/json

{
    "email": "udpatedEmail@gmail.com"
}

#####

// delete user
DELETE http://localhost:3000/auth/1